### PR TITLE
feat: adding darwin arm64 build

### PR DESCRIPTION
**Pull request by kalidax**

### CODE REVIEW

**Comment by sdaveas** [comment]
replaces https://github.com/axelarnetwork/tofnd/pull/304

**Review by talalashraf — APPROVED** [review]
looks good from my side. can we add instructions for people who want to build whatever platform we are missing ?

**Comment by kalidax** [comment]
> looks good from my side. can we add instructions for people who want to build whatever platform we are missing ?

I added a "build " section in the README, should I add more instructions ?

**Review by sdaveas — APPROVED** [review]
Perhaps add the commands to build on each OS at the readme file at a section before [Running the server](https://github.com/axelarnetwork/tofnd#running-the-server).

**Pull request merged**
